### ISSUE TITLE
TypeError: t.encodeABI is not a function

### ISSUE THREAD

**Issue by gino667** [dopex-io/web3-multicall#3]
I am trying to execute a contract function with an eth_call but it reverts with the error,

TypeError: t.encodeABI is not a function
    at \node_modules\@dopex-io\web3-multicall\dist\index.js:1:2436
    at Array.map (<anonymous>)
    at t.i.aggregate (\node_modules\@dopex-io\web3-multicall\dist\index.js:1:2412)
    at main (file:///test/call_test.mjs:21:39)
    at file:///test/call_test.mjs:41:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

**Comment by witherblock** [comment]
Hey, can you share the piece of code you are executing?

**Comment by witherblock** [comment]
Closing due to inactivity
